version: '3.9'

services:
  grafana:
    image: grafana/grafana
    user: root
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - PG_EXPORTER_METRIC_PREFIX=${PG_EXPORTER_METRIC_PREFIX}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/datasources
      - ./grafana/data:/var/lib/grafana
